
server:
  servlet:
    session:
      cookie:
        http-only: true
  port: 8080

spring:
  liquibase:
    change-log: classpath:db/master.xml
    drop-first: false
  datasource:
    url: jdbc:postgresql://localhost:5432/myapp
    username: myapp
    password:
    hikari:
      poolName: Hikari
      auto-commit: false

mybatis:
  mapper-locations: "classpath:mapper/*.xml"
  configuration-properties:
    aggressiveLazyLoading: false
    lazyLoadingEnabled: true
    mapUnderscoreToCamelCase: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui: /swagger-ui-custom.html